// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmXmovHekG4-E82PsWiDzPBfOjF-eHU-4',
    appId: '1:664615811569:android:66cc45cb68139021e86c50',
    messagingSenderId: '664615811569',
    projectId: 'my-notes-mellow-m',
    storageBucket: 'my-notes-mellow-m.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqRKQQhNtIczO-A6riYoH_oi2ckzIPcsg',
    appId: '1:664615811569:ios:b2eb5344e75baed0e86c50',
    messagingSenderId: '664615811569',
    projectId: 'my-notes-mellow-m',
    storageBucket: 'my-notes-mellow-m.appspot.com',
    iosClientId: '664615811569-67p5hhnc70qgdeatu9v7hh0mt9r9j4av.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );
}
